CONCEPTS = ["Array", "String", "Linked List", "Stack", "Queue", "Graph", "Tree", "DP", "OOP"]

COMPANY_TOPICS: dict[str, list[str]] = {
    "google":    ["Array", "Graph", "Tree", "DP", "String"],
    "amazon":    ["Array", "DP", "Tree", "OOP", "Graph"],
    "microsoft": ["Tree", "Graph", "Array", "OOP", "DP"],
    "meta":      ["Array", "Graph", "DP", "String", "Tree"],
    "apple":     ["Array", "String", "Tree", "OOP"],
    "netflix":   ["DP", "Graph", "Array", "OOP"],
    "uber":      ["Graph", "Array", "Queue", "DP"],
    "linkedin":  ["Graph", "Array", "DP", "String"],
    "adobe":     ["Array", "String", "DP", "Tree"],
    "salesforce": ["OOP", "Array", "Tree", "Graph"],
}


def _q(title, desc, examples, constraints, tc, sc, tests, py, js="", java="", cpp="", difficulty=0):
    return {
        "title": title, "description": desc, "examples": examples,
        "constraints": constraints, "time_complexity": tc, "space_complexity": sc,
        "test_cases": tests,
        "starter_code": {"python": py, "javascript": js or "function solve() {}\n",
                         "java": java or "class Solution {}\n", "cpp": cpp or "// cpp\n"},
        "difficulty": difficulty,
    }


CONCEPT_QUESTIONS = {
    "Array": [
        _q(
            "Two Sum",
            "Given an array nums and target, return indices of two numbers that add up to target. Exactly one solution exists.",
            [{"input": "nums=[2,7,11,15], target=9", "output": "[0,1]", "explanation": "nums[0]+nums[1]=9"},
             {"input": "nums=[3,2,4], target=6", "output": "[1,2]", "explanation": "nums[1]+nums[2]=6"}],
            ["2 ≤ nums.length ≤ 10⁴", "-10⁹ ≤ nums[i] ≤ 10⁹", "Exactly one valid answer"],
            "O(n)", "O(n)",
            [{"input": "[2,7,11,15], 9", "expected": "[0, 1]"},
             {"input": "[3,2,4], 6", "expected": "[1, 2]"},
             {"input": "[3,3], 6", "expected": "[0, 1]"},
             {"input": "[1,5,3,2], 4", "expected": "[2, 3]"},
             {"input": "[-1,-2,-3,-4,-5], -8", "expected": "[2, 4]"}],
            "def two_sum(nums, target):\n    # Return list of two indices\n    # Hint: use a hash map\n    pass\n",
            "function twoSum(nums, target) {\n  // return array of two indices\n}\n",
            "class Solution {\n    public int[] twoSum(int[] nums, int target) { return new int[]{}; }\n}\n",
            "vector<int> twoSum(vector<int>& nums, int target) { return {}; }\n",
            difficulty=0,
        ),
        _q(
            "Maximum Subarray",
            "Find the contiguous subarray with the largest sum. Return (start, end, total). Handle all-negative arrays.",
            [{"input": "values=[-2,1,-3,4,-1,2,1,-5,4]", "output": "(3,6,6)", "explanation": "[4,-1,2,1] sums to 6"},
             {"input": "values=[-3,-1,-2]", "output": "(1,1,-1)", "explanation": "All negative, pick least: -1"}],
            ["1 ≤ len(values) ≤ 10⁵", "-10⁴ ≤ values[i] ≤ 10⁴"],
            "O(n)", "O(1)",
            [{"input": "[-2,1,-3,4,-1,2,1,-5,4]", "expected": "(3, 6, 6)"},
             {"input": "[1]", "expected": "(0, 0, 1)"},
             {"input": "[-3,-1,-2]", "expected": "(1, 1, -1)"},
             {"input": "[5,4,-1,7,8]", "expected": "(0, 4, 23)"},
             {"input": "[-1,2,3,-9,4,5,-2]", "expected": "(4, 5, 9)"}],
            "def best_window(values):\n    # Return (start, end, total) — Kadane's algorithm\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Product of Array Except Self",
            "Given an integer array nums, return an array answer such that answer[i] is equal to the product of all elements of nums except nums[i]. Solve in O(n) without division.",
            [{"input": "nums=[1,2,3,4]", "output": "[24,12,8,6]", "explanation": "24=2*3*4, 12=1*3*4, 8=1*2*4, 6=1*2*3"},
             {"input": "nums=[-1,1,0,-3,3]", "output": "[0,0,9,0,0]", "explanation": "Zero in array makes most products zero"},
             {"input": "nums=[2,3]", "output": "[3,2]", "explanation": "Each element is the product of the other"}],
            ["2 ≤ nums.length ≤ 10⁵", "-30 ≤ nums[i] ≤ 30", "The product of any prefix or suffix fits in a 32-bit integer"],
            "O(n)", "O(1) extra space (output array not counted)",
            [{"input": "[1,2,3,4]", "expected": "[24, 12, 8, 6]"},
             {"input": "[-1,1,0,-3,3]", "expected": "[0, 0, 9, 0, 0]"},
             {"input": "[2,3]", "expected": "[3, 2]"},
             {"input": "[1,1,1,1]", "expected": "[1, 1, 1, 1]"},
             {"input": "[0,0]", "expected": "[0, 0]"}],
            "def product_except_self(nums):\n    # Build left-prefix and right-suffix products\n    # Avoid division; use O(1) extra space\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Container With Most Water",
            "Given n non-negative integers representing vertical lines at positions i, find two lines that together with the x-axis form a container that holds the most water.",
            [{"input": "height=[1,8,6,2,5,4,8,3,7]", "output": "49", "explanation": "Lines at index 1 (height 8) and 8 (height 7): min(8,7)*(8-1)=49"},
             {"input": "height=[1,1]", "output": "1", "explanation": "Only two lines, area = min(1,1)*1 = 1"},
             {"input": "height=[4,3,2,1,4]", "output": "16", "explanation": "Lines at index 0 and 4: min(4,4)*4=16"}],
            ["2 ≤ height.length ≤ 10⁵", "0 ≤ height[i] ≤ 10⁴"],
            "O(n)", "O(1)",
            [{"input": "[1,8,6,2,5,4,8,3,7]", "expected": "49"},
             {"input": "[1,1]", "expected": "1"},
             {"input": "[4,3,2,1,4]", "expected": "16"},
             {"input": "[1,2,1]", "expected": "2"},
             {"input": "[2,3,4,5,18,17,6]", "expected": "17"}],
            "def max_area(height):\n    # Two-pointer approach: move the shorter line inward\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Move Zeroes",
            "Given an integer array nums, move all 0s to the end while maintaining the relative order of non-zero elements. Do it in-place.",
            [{"input": "nums=[0,1,0,3,12]", "output": "[1,3,12,0,0]", "explanation": "Non-zeros moved forward, zeros at end"},
             {"input": "nums=[0]", "output": "[0]", "explanation": "Single zero stays"},
             {"input": "nums=[1,2,3]", "output": "[1,2,3]", "explanation": "No zeros, array unchanged"}],
            ["1 ≤ nums.length ≤ 10⁴", "-2³¹ ≤ nums[i] ≤ 2³¹-1"],
            "O(n)", "O(1)",
            [{"input": "[0,1,0,3,12]", "expected": "[1, 3, 12, 0, 0]"},
             {"input": "[0]", "expected": "[0]"},
             {"input": "[1,2,3]", "expected": "[1, 2, 3]"},
             {"input": "[0,0,1]", "expected": "[1, 0, 0]"},
             {"input": "[4,0,0,2,3,0,1]", "expected": "[4, 2, 3, 1, 0, 0, 0]"}],
            "def move_zeroes(nums):\n    # Use a write pointer for non-zero elements\n    # Modify nums in-place; no return needed\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Find the Duplicate Number",
            "Given an array nums of n+1 integers where each integer is in [1, n], find the duplicate number. Use O(1) extra space and do not modify the array.",
            [{"input": "nums=[1,3,4,2,2]", "output": "2", "explanation": "2 appears twice"},
             {"input": "nums=[3,1,3,4,2]", "output": "3", "explanation": "3 appears twice"},
             {"input": "nums=[1,1]", "output": "1", "explanation": "Only two elements, 1 is duplicated"}],
            ["1 ≤ n ≤ 10⁵", "nums.length == n+1", "1 ≤ nums[i] ≤ n", "Only one number is repeated"],
            "O(n)", "O(1)",
            [{"input": "[1,3,4,2,2]", "expected": "2"},
             {"input": "[3,1,3,4,2]", "expected": "3"},
             {"input": "[1,1]", "expected": "1"},
             {"input": "[2,2,2,2,2]", "expected": "2"},
             {"input": "[1,2,3,4,5,3]", "expected": "3"}],
            "def find_duplicate(nums):\n    # Floyd's cycle detection (tortoise and hare)\n    # Treat array as a linked list where nums[i] -> next node\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Best Time to Buy and Sell Stock",
            "Given an array prices where prices[i] is the stock price on day i, return the maximum profit from buying on one day and selling on a later day. Return 0 if no profit is possible.",
            [{"input": "prices=[7,1,5,3,6,4]", "output": "5", "explanation": "Buy on day 2 (price=1), sell on day 5 (price=6): profit=5"},
             {"input": "prices=[7,6,4,3,1]", "output": "0", "explanation": "Prices only decrease; no profit possible"},
             {"input": "prices=[2,4,1]", "output": "2", "explanation": "Buy at 2, sell at 4: profit=2"}],
            ["1 ≤ prices.length ≤ 10⁵", "0 ≤ prices[i] ≤ 10⁴"],
            "O(n)", "O(1)",
            [{"input": "[7,1,5,3,6,4]", "expected": "5"},
             {"input": "[7,6,4,3,1]", "expected": "0"},
             {"input": "[2,4,1]", "expected": "2"},
             {"input": "[1,2]", "expected": "1"},
             {"input": "[3,3,3]", "expected": "0"}],
            "def max_profit(prices):\n    # Track the minimum price seen so far and max profit\n    pass\n",
            difficulty=0,
        ),
        _q(
            "3Sum",
            "Given an integer array nums, return all triplets [nums[i], nums[j], nums[k]] such that i, j, k are distinct and their sum is 0. The solution must not contain duplicate triplets.",
            [{"input": "nums=[-1,0,1,2,-1,-4]", "output": "[[-1,-1,2],[-1,0,1]]", "explanation": "Two unique triplets sum to 0"},
             {"input": "nums=[0,1,1]", "output": "[]", "explanation": "No triplet sums to 0"},
             {"input": "nums=[0,0,0]", "output": "[[0,0,0]]", "explanation": "Only one triplet"}],
            ["3 ≤ nums.length ≤ 3000", "-10⁵ ≤ nums[i] ≤ 10⁵"],
            "O(n²)", "O(n)",
            [{"input": "[-1,0,1,2,-1,-4]", "expected": "[[-1,-1,2],[-1,0,1]]"},
             {"input": "[0,1,1]", "expected": "[]"},
             {"input": "[0,0,0]", "expected": "[[0,0,0]]"},
             {"input": "[-2,0,1,1,2]", "expected": "[[-2,0,2],[-2,1,1]]"},
             {"input": "[-4,-2,-2,-2,0,1,2,2,2,3,3,4,4,6,6]", "expected": "[[-4,-2,6],[-4,0,4],[-4,1,3],[-4,2,2],[-2,-2,4],[-2,0,2]]"}],
            "def three_sum(nums):\n    # Sort + two-pointer for each fixed element\n    # Skip duplicates to avoid repeated triplets\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Subarray Sum Equals K",
            "Given an integer array nums and integer k, return the total number of subarrays whose elements sum to k.",
            [{"input": "nums=[1,1,1], k=2", "output": "2", "explanation": "Subarrays [1,1] at indices (0,1) and (1,2)"},
             {"input": "nums=[1,2,3], k=3", "output": "2", "explanation": "Subarrays [3] and [1,2]"},
             {"input": "nums=[1], k=0", "output": "0", "explanation": "No subarray sums to 0"}],
            ["1 ≤ nums.length ≤ 2×10⁴", "-1000 ≤ nums[i] ≤ 1000", "-10⁷ ≤ k ≤ 10⁷"],
            "O(n)", "O(n)",
            [{"input": "[1,1,1], 2", "expected": "2"},
             {"input": "[1,2,3], 3", "expected": "2"},
             {"input": "[1], 0", "expected": "0"},
             {"input": "[-1,-1,1], 0", "expected": "1"},
             {"input": "[1,2,1,2,1], 3", "expected": "4"}],
            "def subarray_sum(nums, k):\n    # Prefix sum + hash map: count how many prefix[i] == prefix[j] - k\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Spiral Matrix",
            "Given an m×n matrix, return all elements in spiral order (clockwise from top-left).",
            [{"input": "matrix=[[1,2,3],[4,5,6],[7,8,9]]", "output": "[1,2,3,6,9,8,7,4,5]", "explanation": "Spiral clockwise from top-left"},
             {"input": "matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]", "output": "[1,2,3,4,8,12,11,10,9,5,6,7]", "explanation": "4 columns, 3 rows spiral"},
             {"input": "matrix=[[1]]", "output": "[1]", "explanation": "Single element"}],
            ["m == matrix.length", "n == matrix[i].length", "1 ≤ m, n ≤ 10", "-100 ≤ matrix[i][j] ≤ 100"],
            "O(m×n)", "O(1) extra space",
            [{"input": "[[1,2,3],[4,5,6],[7,8,9]]", "expected": "[1,2,3,6,9,8,7,4,5]"},
             {"input": "[[1,2,3,4],[5,6,7,8],[9,10,11,12]]", "expected": "[1,2,3,4,8,12,11,10,9,5,6,7]"},
             {"input": "[[1]]", "expected": "[1]"},
             {"input": "[[1,2],[3,4]]", "expected": "[1,2,4,3]"},
             {"input": "[[1,2,3]]", "expected": "[1,2,3]"}],
            "def spiral_order(matrix):\n    # Shrink boundaries: top, bottom, left, right\n    # Traverse top row -> right col -> bottom row -> left col, then shrink\n    pass\n",
            difficulty=1,
        ),
    ],
    "String": [
        _q(
            "Longest Substring Without Repeating Characters",
            "Given string s, find the length of the longest substring without repeating characters.",
            [{"input": 's="abcabcbb"', "output": "3", "explanation": '"abc" has length 3'},
             {"input": 's="bbbbb"', "output": "1", "explanation": 'Only "b"'},
             {"input": 's="pwwkew"', "output": "3", "explanation": '"wke"'}],
            ["0 ≤ s.length ≤ 5×10⁴", "s consists of English letters, digits, symbols"],
            "O(n)", "O(min(n,m))",
            [{"input": '"abcabcbb"', "expected": "3"}, {"input": '"bbbbb"', "expected": "1"},
             {"input": '"pwwkew"', "expected": "3"}, {"input": '""', "expected": "0"},
             {"input": '"abcdef"', "expected": "6"}],
            "def length_of_longest_substring(s):\n    # Sliding window approach\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Valid Anagram",
            "Given strings s and t, return True if t is an anagram of s, False otherwise.",
            [{"input": 's="anagram", t="nagaram"', "output": "True", "explanation": "Same character counts"},
             {"input": 's="rat", t="car"', "output": "False", "explanation": "Different characters"}],
            ["1 ≤ s.length, t.length ≤ 5×10⁴", "s and t consist of lowercase letters"],
            "O(n)", "O(1)",
            [{"input": '"anagram", "nagaram"', "expected": "True"},
             {"input": '"rat", "car"', "expected": "False"},
             {"input": '"a", "a"', "expected": "True"},
             {"input": '"ab", "a"', "expected": "False"},
             {"input": '"listen", "silent"', "expected": "True"}],
            "def is_anagram(s, t):\n    # Return True if anagram, False otherwise\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Reverse Words in a String",
            "Given an input string s, reverse the order of the words. Words are separated by spaces; the result should have a single space between words with no leading or trailing spaces.",
            [{"input": 's="the sky is blue"', "output": '"blue is sky the"', "explanation": "Words reversed in order"},
             {"input": 's="  hello world  "', "output": '"world hello"', "explanation": "Leading/trailing spaces removed"},
             {"input": 's="a good   example"', "output": '"example good a"', "explanation": "Multiple spaces collapsed"}],
            ["1 ≤ s.length ≤ 10⁴", "s contains English letters and spaces", "At least one word in s"],
            "O(n)", "O(n)",
            [{"input": '"the sky is blue"', "expected": '"blue is sky the"'},
             {"input": '"  hello world  "', "expected": '"world hello"'},
             {"input": '"a good   example"', "expected": '"example good a"'},
             {"input": '"singleword"', "expected": '"singleword"'},
             {"input": '"  spaces  everywhere  "', "expected": '"everywhere spaces"'}],
            "def reverse_words(s):\n    # Split on whitespace, reverse, join with single space\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Valid Palindrome",
            "A phrase is a palindrome if, after converting all uppercase letters to lowercase and removing all non-alphanumeric characters, it reads the same forward and backward. Return True if s is a palindrome.",
            [{"input": 's="A man, a plan, a canal: Panama"', "output": "True", "explanation": "amanaplanacanalpanama is a palindrome"},
             {"input": 's="race a car"', "output": "False", "explanation": "raceacar is not a palindrome"},
             {"input": 's=" "', "output": "True", "explanation": "Empty string after filtering is a palindrome"}],
            ["1 ≤ s.length ≤ 2×10⁵", "s consists of printable ASCII characters"],
            "O(n)", "O(1)",
            [{"input": '"A man, a plan, a canal: Panama"', "expected": "True"},
             {"input": '"race a car"', "expected": "False"},
             {"input": '" "', "expected": "True"},
             {"input": '"No lemon, no melon"', "expected": "True"},
             {"input": '"0P"', "expected": "False"}],
            "def is_palindrome(s):\n    # Use two pointers, skip non-alphanumeric chars\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Longest Palindromic Substring",
            "Given string s, return the longest palindromic substring. A palindrome reads the same forward and backward.",
            [{"input": 's="babad"', "output": '"bab"', "explanation": '"bab" or "aba" are both valid answers'},
             {"input": 's="cbbd"', "output": '"bb"', "explanation": '"bb" is the longest palindrome'},
             {"input": 's="a"', "output": '"a"', "explanation": "Single character is always a palindrome"}],
            ["1 ≤ s.length ≤ 1000", "s consists of digits and English letters"],
            "O(n²)", "O(1)",
            [{"input": '"babad"', "expected": '"bab"'},
             {"input": '"cbbd"', "expected": '"bb"'},
             {"input": '"a"', "expected": '"a"'},
             {"input": '"racecar"', "expected": '"racecar"'},
             {"input": '"abcba"', "expected": '"abcba"'}],
            "def longest_palindrome(s):\n    # Expand around center: try each character (and pair) as center\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Roman to Integer",
            "Convert a Roman numeral string to an integer. Roman numerals use: I=1, V=5, X=10, L=50, C=100, D=500, M=1000. When a smaller value precedes a larger one, subtract it.",
            [{"input": 's="III"', "output": "3", "explanation": "I+I+I = 3"},
             {"input": 's="LVIII"', "output": "58", "explanation": "L=50, V=5, III=3"},
             {"input": 's="MCMXCIV"', "output": "1994", "explanation": "M=1000, CM=900, XC=90, IV=4"}],
            ["1 ≤ s.length ≤ 15", "s contains only valid Roman numeral characters", "1 ≤ answer ≤ 3999"],
            "O(n)", "O(1)",
            [{"input": '"III"', "expected": "3"},
             {"input": '"LVIII"', "expected": "58"},
             {"input": '"MCMXCIV"', "expected": "1994"},
             {"input": '"IV"', "expected": "4"},
             {"input": '"IX"', "expected": "9"}],
            "def roman_to_int(s):\n    # Map each symbol; subtract when smaller value precedes larger\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Group Anagrams",
            "Given an array of strings strs, group the anagrams together. Return the groups in any order.",
            [{"input": 'strs=["eat","tea","tan","ate","nat","bat"]', "output": '[["bat"],["nat","tan"],["ate","eat","tea"]]', "explanation": "Three anagram groups"},
             {"input": 'strs=[""]', "output": '[[""]]', "explanation": "Single empty string"},
             {"input": 'strs=["a"]', "output": '[["a"]]', "explanation": "Single character"}],
            ["1 ≤ strs.length ≤ 10⁴", "0 ≤ strs[i].length ≤ 100", "strs[i] consists of lowercase letters"],
            "O(n × k log k)", "O(n × k)",
            [{"input": '["eat","tea","tan","ate","nat","bat"]', "expected": "3 groups"},
             {"input": '[""]', "expected": '[[""]]'},
             {"input": '["a"]', "expected": '[["a"]]'},
             {"input": '["abc","bca","cab","xyz"]', "expected": "2 groups"},
             {"input": '["ab","ba","cd","dc","ef"]', "expected": "3 groups"}],
            "def group_anagrams(strs):\n    # Key = sorted(word); group words by key in a hash map\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Minimum Window Substring",
            "Given strings s and t, return the minimum window substring of s that contains all characters of t. Return empty string if no such window exists.",
            [{"input": 's="ADOBECODEBANC", t="ABC"', "output": '"BANC"', "explanation": "Shortest window containing A, B, C"},
             {"input": 's="a", t="a"', "output": '"a"', "explanation": "Entire string is the minimum window"},
             {"input": 's="a", t="aa"', "output": '""', "explanation": "t has two a's but s only has one"}],
            ["m == s.length", "n == t.length", "1 ≤ m, n ≤ 10⁵", "s and t consist of uppercase and lowercase letters"],
            "O(m + n)", "O(m + n)",
            [{"input": '"ADOBECODEBANC", "ABC"', "expected": '"BANC"'},
             {"input": '"a", "a"', "expected": '"a"'},
             {"input": '"a", "aa"', "expected": '""'},
             {"input": '"aa", "aa"', "expected": '"aa"'},
             {"input": '"AZBCDE", "AC"', "expected": '"AZBC"'}],
            "def min_window(s, t):\n    # Sliding window: expand right until valid, shrink left to minimize\n    # Use frequency maps for t chars and current window\n    pass\n",
            difficulty=2,
        ),
        _q(
            "Longest Repeating Character Replacement",
            "Given a string s and integer k, you can replace at most k characters. Return the length of the longest substring containing the same letter after replacements.",
            [{"input": 's="ABAB", k=2', "output": "4", "explanation": "Replace 2 A's or B's to get 'AAAA' or 'BBBB'"},
             {"input": 's="AABABBA", k=1', "output": "4", "explanation": "Replace the one B in 'AABA' → 'AAAA', length 4"},
             {"input": 's="AAAA", k=0', "output": "4", "explanation": "No replacements needed"}],
            ["1 ≤ s.length ≤ 10⁵", "s consists of uppercase letters", "0 ≤ k ≤ s.length"],
            "O(n)", "O(1)",
            [{"input": '"ABAB", 2', "expected": "4"},
             {"input": '"AABABBA", 1', "expected": "4"},
             {"input": '"AAAA", 0', "expected": "4"},
             {"input": '"ABCD", 2', "expected": "3"},
             {"input": '"AAABBC", 2', "expected": "5"}],
            "def character_replacement(s, k):\n    # Sliding window: window_size - max_freq <= k means valid\n    pass\n",
            difficulty=1,
        ),
    ],
    "Linked List": [
        _q(
            "Reverse Linked List",
            "Given the head of a singly linked list, reverse it and return the new head.",
            [{"input": "head=[1,2,3,4,5]", "output": "[5,4,3,2,1]", "explanation": "Reversed in place"},
             {"input": "head=[1,2]", "output": "[2,1]", "explanation": "Two nodes swapped"},
             {"input": "head=[]", "output": "[]", "explanation": "Empty list"}],
            ["0 ≤ Number of nodes ≤ 5000", "-5000 ≤ Node.val ≤ 5000"],
            "O(n)", "O(1)",
            [{"input": "[1,2,3,4,5]", "expected": "[5,4,3,2,1]"},
             {"input": "[1,2]", "expected": "[2,1]"},
             {"input": "[]", "expected": "[]"},
             {"input": "[1]", "expected": "[1]"},
             {"input": "[1,2,3]", "expected": "[3,2,1]"}],
            "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef reverse_list(head):\n    # Return new head after reversal\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Detect Cycle in Linked List",
            "Given head of a linked list, return True if there is a cycle, False otherwise. Use O(1) space.",
            [{"input": "head=[3,2,0,-4], pos=1", "output": "True", "explanation": "Tail connects to index 1"},
             {"input": "head=[1,2], pos=-1", "output": "False", "explanation": "No cycle"}],
            ["0 ≤ Number of nodes ≤ 10⁴", "-10⁵ ≤ Node.val ≤ 10⁵"],
            "O(n)", "O(1)",
            [{"input": "[3,2,0,-4], cycle_at=1", "expected": "True"},
             {"input": "[1,2], cycle_at=-1", "expected": "False"},
             {"input": "[], cycle_at=-1", "expected": "False"},
             {"input": "[1], cycle_at=-1", "expected": "False"},
             {"input": "[1,1,1,1], cycle_at=0", "expected": "True"}],
            "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef has_cycle(head):\n    # Floyd's tortoise and hare — O(1) space\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Merge Two Sorted Lists",
            "Merge two sorted linked lists and return the head of the merged sorted list. The list is made by splicing together the nodes of the two lists.",
            [{"input": "list1=[1,2,4], list2=[1,3,4]", "output": "[1,1,2,3,4,4]", "explanation": "All nodes merged in sorted order"},
             {"input": "list1=[], list2=[]", "output": "[]", "explanation": "Both empty, result is empty"},
             {"input": "list1=[], list2=[0]", "output": "[0]", "explanation": "One empty list, return the other"}],
            ["0 ≤ length of each list ≤ 50", "-100 ≤ Node.val ≤ 100", "Both lists are sorted in non-decreasing order"],
            "O(m+n)", "O(1)",
            [{"input": "[1,2,4], [1,3,4]", "expected": "[1,1,2,3,4,4]"},
             {"input": "[], []", "expected": "[]"},
             {"input": "[], [0]", "expected": "[0]"},
             {"input": "[1,3,5], [2,4,6]", "expected": "[1,2,3,4,5,6]"},
             {"input": "[5], [1,2,3]", "expected": "[1,2,3,5]"}],
            "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef merge_two_lists(list1, list2):\n    # Use a dummy head and pointer to build merged list\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Remove Nth Node From End",
            "Given the head of a linked list, remove the nth node from the end of the list and return the head. Do it in one pass.",
            [{"input": "head=[1,2,3,4,5], n=2", "output": "[1,2,3,5]", "explanation": "4th node (2nd from end) removed"},
             {"input": "head=[1], n=1", "output": "[]", "explanation": "Only node removed"},
             {"input": "head=[1,2], n=1", "output": "[1]", "explanation": "Last node removed"}],
            ["1 ≤ length of list ≤ 30", "0 ≤ Node.val ≤ 100", "1 ≤ n ≤ length of list"],
            "O(n)", "O(1)",
            [{"input": "[1,2,3,4,5], 2", "expected": "[1,2,3,5]"},
             {"input": "[1], 1", "expected": "[]"},
             {"input": "[1,2], 1", "expected": "[1]"},
             {"input": "[1,2,3], 3", "expected": "[2,3]"},
             {"input": "[1,2,3,4], 2", "expected": "[1,2,4]"}],
            "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef remove_nth_from_end(head, n):\n    # Two-pointer technique: advance fast pointer n steps ahead\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Middle of the Linked List",
            "Given the head of a singly linked list, return the middle node. If there are two middle nodes, return the second middle node.",
            [{"input": "head=[1,2,3,4,5]", "output": "[3,4,5]", "explanation": "Middle node is 3"},
             {"input": "head=[1,2,3,4,5,6]", "output": "[4,5,6]", "explanation": "Two middles: 3 and 4; return second"},
             {"input": "head=[1]", "output": "[1]", "explanation": "Single node is the middle"}],
            ["1 ≤ Number of nodes ≤ 100", "1 ≤ Node.val ≤ 100"],
            "O(n)", "O(1)",
            [{"input": "[1,2,3,4,5]", "expected": "[3,4,5]"},
             {"input": "[1,2,3,4,5,6]", "expected": "[4,5,6]"},
             {"input": "[1]", "expected": "[1]"},
             {"input": "[1,2]", "expected": "[2]"},
             {"input": "[1,2,3]", "expected": "[2,3]"}],
            "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef middle_node(head):\n    # Slow and fast pointer: fast moves 2x, slow moves 1x\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Add Two Numbers",
            "Two non-empty linked lists represent two non-negative integers stored in reverse order. Add the two numbers and return the sum as a linked list in reverse order.",
            [{"input": "l1=[2,4,3], l2=[5,6,4]", "output": "[7,0,8]", "explanation": "342 + 465 = 807, stored as [7,0,8]"},
             {"input": "l1=[0], l2=[0]", "output": "[0]", "explanation": "0 + 0 = 0"},
             {"input": "l1=[9,9,9,9], l2=[9,9,9]", "output": "[8,9,9,0,1]", "explanation": "9999 + 999 = 10998"}],
            ["1 ≤ length of each list ≤ 100", "0 ≤ Node.val ≤ 9", "No leading zeros except the number 0"],
            "O(max(m,n))", "O(max(m,n))",
            [{"input": "[2,4,3], [5,6,4]", "expected": "[7,0,8]"},
             {"input": "[0], [0]", "expected": "[0]"},
             {"input": "[9,9,9,9], [9,9,9]", "expected": "[8,9,9,0,1]"},
             {"input": "[1], [9,9]", "expected": "[0,0,1]"},
             {"input": "[5], [5]", "expected": "[0,1]"}],
            "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef add_two_numbers(l1, l2):\n    # Simulate addition digit by digit with carry\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Find Cycle Entry Point",
            "Given the head of a linked list that may contain a cycle, return the node where the cycle begins. Return None if no cycle exists. Use O(1) space.",
            [{"input": "head=[3,2,0,-4], pos=1", "output": "node at index 1 (val=2)", "explanation": "Cycle starts at node with value 2"},
             {"input": "head=[1,2], pos=0", "output": "node at index 0 (val=1)", "explanation": "Cycle starts at head"},
             {"input": "head=[1], pos=-1", "output": "None", "explanation": "No cycle exists"}],
            ["0 ≤ Number of nodes ≤ 10⁴", "-10⁵ ≤ Node.val ≤ 10⁵", "pos is -1 or a valid index"],
            "O(n)", "O(1)",
            [{"input": "[3,2,0,-4], cycle_at=1", "expected": "2"},
             {"input": "[1,2], cycle_at=0", "expected": "1"},
             {"input": "[1], cycle_at=-1", "expected": "None"},
             {"input": "[1,2,3,4,5], cycle_at=2", "expected": "3"},
             {"input": "[1,2,3], cycle_at=-1", "expected": "None"}],
            "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef detect_cycle(head):\n    # Phase 1: Floyd's algorithm to detect meeting point\n    # Phase 2: Move one pointer to head; advance both 1 step at a time to find entry\n    pass\n",
            difficulty=2,
        ),
        _q(
            "Reorder List",
            "Given the head of a singly linked list L0→L1→…→Ln, reorder it to L0→Ln→L1→Ln-1→L2→Ln-2→…. Do it in-place without altering node values.",
            [{"input": "head=[1,2,3,4]", "output": "[1,4,2,3]", "explanation": "First and last interleaved"},
             {"input": "head=[1,2,3,4,5]", "output": "[1,5,2,4,3]", "explanation": "Middle node stays in place"},
             {"input": "head=[1]", "output": "[1]", "explanation": "Single node unchanged"}],
            ["1 ≤ Number of nodes ≤ 5×10⁴", "1 ≤ Node.val ≤ 1000"],
            "O(n)", "O(1)",
            [{"input": "[1,2,3,4]", "expected": "[1,4,2,3]"},
             {"input": "[1,2,3,4,5]", "expected": "[1,5,2,4,3]"},
             {"input": "[1]", "expected": "[1]"},
             {"input": "[1,2]", "expected": "[1,2]"},
             {"input": "[1,2,3]", "expected": "[1,3,2]"}],
            "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef reorder_list(head):\n    # Step 1: Find middle (slow/fast pointers)\n    # Step 2: Reverse second half\n    # Step 3: Merge two halves\n    pass\n",
            difficulty=1,
        ),
    ],
    "Stack": [
        _q(
            "Valid Parentheses",
            "Given a string containing only '(', ')', '{', '}', '[', ']', determine if the input string is valid.",
            [{"input": 's="()"', "output": "True", "explanation": "Matching pair"},
             {"input": 's="()[]{}"', "output": "True", "explanation": "All pairs match"},
             {"input": 's="(]"', "output": "False", "explanation": "Mismatched brackets"}],
            ["1 ≤ s.length ≤ 10⁴", "s consists of parentheses only"],
            "O(n)", "O(n)",
            [{"input": '"()"', "expected": "True"}, {"input": '"()[]{}"', "expected": "True"},
             {"input": '"(]"', "expected": "False"}, {"input": '"([)]"', "expected": "False"},
             {"input": '"{[]}"', "expected": "True"}],
            "def is_valid(s):\n    # Use a stack to match opening/closing brackets\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Min Stack",
            "Design a stack that supports push, pop, top, and retrieving the minimum element in O(1) time.",
            [{"input": 'MinStack(); push(-2); push(0); push(-3); getMin()', "output": "-3", "explanation": "Minimum is -3"},
             {"input": 'pop(); top(); getMin()', "output": "0, -2", "explanation": "After pop, top=0, min=-2"}],
            ["All operations run in O(1)", "-2³¹ ≤ val ≤ 2³¹-1", "pop/top/getMin called on non-empty stack"],
            "O(1)", "O(n)",
            [{"input": "push(-2),push(0),push(-3),getMin()", "expected": "-3"},
             {"input": "push(1),push(2),getMin(),pop(),getMin()", "expected": "1"},
             {"input": "push(0),push(1),push(0),getMin(),pop(),getMin()", "expected": "0"},
             {"input": "push(5),top()", "expected": "5"},
             {"input": "push(2),push(1),pop(),top()", "expected": "2"}],
            "class MinStack:\n    def __init__(self):\n        # Use an auxiliary stack to track minimums\n        pass\n\n    def push(self, val):\n        pass\n\n    def pop(self):\n        pass\n\n    def top(self):\n        pass\n\n    def get_min(self):\n        pass\n",
            difficulty=1,
        ),
        _q(
            "Daily Temperatures",
            "Given an array temperatures, return an array answer where answer[i] is the number of days until a warmer temperature. If no future warmer day exists, answer[i] = 0.",
            [{"input": "temperatures=[73,74,75,71,69,72,76,73]", "output": "[1,1,4,2,1,1,0,0]", "explanation": "Day 0: next warmer is day 1 (+1), day 2: next warmer is day 6 (+4)"},
             {"input": "temperatures=[30,40,50,60]", "output": "[1,1,1,0]", "explanation": "Each day is warmer than previous"},
             {"input": "temperatures=[30,60,90]", "output": "[1,1,0]", "explanation": "Last day has no warmer future day"}],
            ["1 ≤ temperatures.length ≤ 10⁵", "30 ≤ temperatures[i] ≤ 100"],
            "O(n)", "O(n)",
            [{"input": "[73,74,75,71,69,72,76,73]", "expected": "[1,1,4,2,1,1,0,0]"},
             {"input": "[30,40,50,60]", "expected": "[1,1,1,0]"},
             {"input": "[30,60,90]", "expected": "[1,1,0]"},
             {"input": "[90,60,30]", "expected": "[0,0,0]"},
             {"input": "[50,50,50]", "expected": "[0,0,0]"}],
            "def daily_temperatures(temperatures):\n    # Monotonic decreasing stack stores indices\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Evaluate Reverse Polish Notation",
            "Evaluate an expression in Reverse Polish Notation (postfix). Operators are +, -, *, /. Division truncates toward zero.",
            [{"input": 'tokens=["2","1","+","3","*"]', "output": "9", "explanation": "((2+1)*3) = 9"},
             {"input": 'tokens=["4","13","5","/","+"]', "output": "6", "explanation": "4 + (13/5) = 4 + 2 = 6"},
             {"input": 'tokens=["10","6","9","3","+","-11","*","/","*","17","+","5","+"]', "output": "22", "explanation": "Complex expression evaluates to 22"}],
            ["1 ≤ tokens.length ≤ 10⁴", "tokens[i] is an integer or one of +, -, *, /", "Valid RPN expression guaranteed"],
            "O(n)", "O(n)",
            [{"input": '["2","1","+","3","*"]', "expected": "9"},
             {"input": '["4","13","5","/","+"]', "expected": "6"},
             {"input": '["3","4","+","2","*","7","/"]', "expected": "2"},
             {"input": '["5","1","2","+","4","*","+","3","-"]', "expected": "14"},
             {"input": '["2","3","*"]', "expected": "6"}],
            "def eval_rpn(tokens):\n    # Use a stack; push numbers, pop two on operator\n    # int() truncates toward zero for division\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Next Greater Element I",
            "Given two arrays nums1 and nums2 where nums1 is a subset of nums2, find the next greater element for each element in nums1 within nums2. Return -1 if none exists.",
            [{"input": "nums1=[4,1,2], nums2=[1,3,4,2]", "output": "[-1,3,-1]", "explanation": "4->no greater, 1->3, 2->no greater"},
             {"input": "nums1=[2,4], nums2=[1,2,3,4]", "output": "[3,-1]", "explanation": "2->3, 4->no greater"},
             {"input": "nums1=[1], nums2=[1,2]", "output": "[2]", "explanation": "Next greater after 1 is 2"}],
            ["1 ≤ nums1.length ≤ nums2.length ≤ 1000", "0 ≤ nums1[i], nums2[i] ≤ 10⁴", "All values in nums2 are unique"],
            "O(n)", "O(n)",
            [{"input": "[4,1,2], [1,3,4,2]", "expected": "[-1,3,-1]"},
             {"input": "[2,4], [1,2,3,4]", "expected": "[3,-1]"},
             {"input": "[1], [1,2]", "expected": "[2]"},
             {"input": "[3], [3]", "expected": "[-1]"},
             {"input": "[1,3,5,2,4], [6,5,4,3,2,1,7]", "expected": "[7,7,7,7,7]"}],
            "def next_greater_element(nums1, nums2):\n    # Monotonic stack on nums2 to precompute next greater\n    # Then look up each nums1 element in the map\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Largest Rectangle in Histogram",
            "Given an array of integers heights representing the histogram bar heights (width=1 each), return the area of the largest rectangle.",
            [{"input": "heights=[2,1,5,6,2,3]", "output": "10", "explanation": "Rectangle of height 5 spanning bars 3 and 4: area=10"},
             {"input": "heights=[2,4]", "output": "4", "explanation": "Taller bar alone: 4×1=4"},
             {"input": "heights=[1,1,1,1]", "output": "4", "explanation": "Full width at height 1: area=4"}],
            ["1 ≤ heights.length ≤ 10⁵", "0 ≤ heights[i] ≤ 10⁴"],
            "O(n)", "O(n)",
            [{"input": "[2,1,5,6,2,3]", "expected": "10"},
             {"input": "[2,4]", "expected": "4"},
             {"input": "[1,1,1,1]", "expected": "4"},
             {"input": "[6,2,5,4,5,1,6]", "expected": "12"},
             {"input": "[0,9]", "expected": "9"}],
            "def largest_rectangle_area(heights):\n    # Monotonic increasing stack; pop when current bar is shorter\n    # On pop, width = current_index - stack_top - 1\n    pass\n",
            difficulty=2,
        ),
        _q(
            "Car Fleet",
            "n cars travel to a destination at position target. Each car has a position and speed. A faster car catching a slower one forms a fleet. Return the number of fleets that arrive.",
            [{"input": "target=12, position=[10,8,0,5,3], speed=[2,4,1,1,3]", "output": "3", "explanation": "Three fleets reach the destination"},
             {"input": "target=10, position=[3], speed=[3]", "output": "1", "explanation": "Single car = single fleet"},
             {"input": "target=100, position=[0,2,4], speed=[4,2,1]", "output": "1", "explanation": "All cars merge into one fleet"}],
            ["n == position.length == speed.length", "1 ≤ n ≤ 10⁵", "0 < target ≤ 10⁶", "All positions are distinct"],
            "O(n log n)", "O(n)",
            [{"input": "12, [10,8,0,5,3], [2,4,1,1,3]", "expected": "3"},
             {"input": "10, [3], [3]", "expected": "1"},
             {"input": "100, [0,2,4], [4,2,1]", "expected": "1"},
             {"input": "10, [6,8], [3,2]", "expected": "2"},
             {"input": "10, [0,4,2], [2,1,3]", "expected": "1"}],
            "def car_fleet(target, position, speed):\n    # Sort cars by position descending\n    # Use a stack: if time for current car >= top of stack, it merges\n    pass\n",
            difficulty=1,
        ),
    ],
    "Queue": [
        _q(
            "Moving Average from Data Stream",
            "Given a stream of integers and window size k, calculate the moving average of all integers in the sliding window.",
            [{"input": "k=3, stream=[1,10,3,5]", "output": "[1.0,5.5,4.67,6.0]", "explanation": "Averages of each window"},
             {"input": "k=1, stream=[4,8,2]", "output": "[4.0,8.0,2.0]", "explanation": "Window of 1 = value itself"}],
            ["1 ≤ k ≤ 1000", "-10⁵ ≤ val ≤ 10⁵"],
            "O(1) per insert", "O(k)",
            [{"input": "k=3, [1,10,3,5]", "expected": "[1.0, 5.5, 4.67, 6.0]"},
             {"input": "k=1, [4,8,2]", "expected": "[4.0, 8.0, 2.0]"},
             {"input": "k=2, [1,2,3]", "expected": "[1.0, 1.5, 2.5]"},
             {"input": "k=3, [5]", "expected": "[5.0]"},
             {"input": "k=2, [10,20,30,40]", "expected": "[10.0, 15.0, 25.0, 35.0]"}],
            "from collections import deque\n\nclass MovingAverage:\n    def __init__(self, size):\n        # Use a deque of fixed size\n        pass\n\n    def next(self, val):\n        # Return current moving average\n        pass\n",
            difficulty=0,
        ),
        _q(
            "Task Scheduler",
            "Given a list of tasks and cooldown n, find minimum intervals CPU needs to finish all tasks. Same task must be n intervals apart.",
            [{"input": 'tasks=["A","A","A","B","B","B"], n=2', "output": "8", "explanation": "A->B->idle->A->B->idle->A->B"},
             {"input": 'tasks=["A","A","A","B","B","B"], n=0', "output": "6", "explanation": "No cooldown needed"}],
            ["1 ≤ tasks.length ≤ 10⁴", "tasks[i] is uppercase letter", "0 ≤ n ≤ 100"],
            "O(n)", "O(1)",
            [{"input": '["A","A","A","B","B","B"], 2', "expected": "8"},
             {"input": '["A","A","A","B","B","B"], 0', "expected": "6"},
             {"input": '["A","A","A","A","A","A","B","C","D","E","F","G"], 2', "expected": "16"},
             {"input": '["A"], 0', "expected": "1"},
             {"input": '["A","A","B","B"], 2', "expected": "5"}],
            "def least_interval(tasks, n):\n    # Use frequency counts and greedy approach\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Design Circular Queue",
            "Design a circular queue with fixed capacity. Implement enQueue, deQueue, Front, Rear, isEmpty, isFull. A circular queue reuses space freed by dequeued elements.",
            [{"input": "MyCircularQueue(3); enQueue(1); enQueue(2); enQueue(3); enQueue(4); Rear(); isFull(); deQueue(); enQueue(4); Rear()", "output": "true,false,true,true,4", "explanation": "Queue full at 3 items; after dequeue, 4 can be enqueued"},
             {"input": "MyCircularQueue(1); enQueue(1); isFull(); deQueue(); isEmpty()", "output": "true,true,true", "explanation": "Capacity 1 fills and empties correctly"}],
            ["1 ≤ k ≤ 1000", "0 ≤ value ≤ 1000", "At most 3000 calls total"],
            "O(1) per operation", "O(k)",
            [{"input": "cap=3,enQueue(1),enQueue(2),enQueue(3),isFull()", "expected": "True"},
             {"input": "cap=3,enQueue(1),deQueue(),isEmpty()", "expected": "True"},
             {"input": "cap=2,enQueue(5),Rear()", "expected": "5"},
             {"input": "cap=3,enQueue(1),enQueue(2),deQueue(),enQueue(3),Front()", "expected": "2"},
             {"input": "cap=1,enQueue(7),Front(),Rear()", "expected": "7"}],
            "class MyCircularQueue:\n    def __init__(self, k):\n        # Use a fixed-size list with head and tail pointers\n        pass\n\n    def enQueue(self, value):\n        # Add to rear; return False if full\n        pass\n\n    def deQueue(self):\n        # Remove from front; return False if empty\n        pass\n\n    def Front(self):\n        # Return front element or -1 if empty\n        pass\n\n    def Rear(self):\n        # Return rear element or -1 if empty\n        pass\n\n    def isEmpty(self):\n        pass\n\n    def isFull(self):\n        pass\n",
            difficulty=1,
        ),
        _q(
            "Implement Queue Using Stacks",
            "Implement a FIFO queue using only two stacks. Implement push, pop, peek, and empty operations.",
            [{"input": "push(1); push(2); peek(); pop(); empty()", "output": "1, 1, False", "explanation": "peek returns front (1), pop removes front (1), not empty after"},
             {"input": "push(1); pop(); empty()", "output": "1, True", "explanation": "After popping only element, queue is empty"}],
            ["1 ≤ x ≤ 9", "At most 100 calls total", "pop and peek called only on non-empty queues"],
            "O(1) amortized per operation", "O(n)",
            [{"input": "push(1),push(2),peek()", "expected": "1"},
             {"input": "push(1),push(2),pop()", "expected": "1"},
             {"input": "push(1),pop(),empty()", "expected": "True"},
             {"input": "push(3),push(4),pop(),peek()", "expected": "4"},
             {"input": "push(5),empty()", "expected": "False"}],
            "class MyQueue:\n    def __init__(self):\n        # Use two stacks: input stack and output stack\n        pass\n\n    def push(self, x):\n        # Push to input stack\n        pass\n\n    def pop(self):\n        # Move input to output if output empty, then pop\n        pass\n\n    def peek(self):\n        # Return front element without removing\n        pass\n\n    def empty(self):\n        pass\n",
            difficulty=0,
        ),
        _q(
            "Sliding Window Maximum",
            "Given an integer array nums and window size k, return the maximum value in each sliding window of size k.",
            [{"input": "nums=[1,3,-1,-3,5,3,6,7], k=3", "output": "[3,3,5,5,6,7]", "explanation": "Max in each window of 3"},
             {"input": "nums=[1], k=1", "output": "[1]", "explanation": "Single element window"},
             {"input": "nums=[1,-1], k=1", "output": "[1,-1]", "explanation": "Each element is its own window"}],
            ["1 ≤ nums.length ≤ 10⁵", "-10⁴ ≤ nums[i] ≤ 10⁴", "1 ≤ k ≤ nums.length"],
            "O(n)", "O(k)",
            [{"input": "[1,3,-1,-3,5,3,6,7], 3", "expected": "[3,3,5,5,6,7]"},
             {"input": "[1], 1", "expected": "[1]"},
             {"input": "[1,-1], 1", "expected": "[1,-1]"},
             {"input": "[9,8,7,6,5], 2", "expected": "[9,8,7,6]"},
             {"input": "[1,2,3,4,5], 3", "expected": "[3,4,5]"}],
            "from collections import deque\n\ndef max_sliding_window(nums, k):\n    # Monotonic deque stores indices in decreasing order of values\n    # Front of deque is always the max of current window\n    pass\n",
            difficulty=2,
        ),
        _q(
            "Number of Recent Calls",
            "Implement a RecentCounter class that counts requests within the last 3000 milliseconds. ping(t) adds a new request at time t and returns the number of requests in [t-3000, t].",
            [{"input": "ping(1); ping(100); ping(3001); ping(3002)", "output": "1, 2, 3, 3", "explanation": "ping(3002): requests at 100,3001,3002 are within [2,3002]"},
             {"input": "ping(10000); ping(10001)", "output": "1, 2", "explanation": "Both calls are within 3000ms of each other"}],
            ["1 ≤ t ≤ 10⁹", "Each call to ping uses a strictly increasing t", "At most 10⁴ calls to ping"],
            "O(1) amortized", "O(n)",
            [{"input": "ping(1)", "expected": "1"},
             {"input": "ping(1),ping(100),ping(3001)", "expected": "3"},
             {"input": "ping(1),ping(100),ping(3001),ping(3002)", "expected": "3"},
             {"input": "ping(5000),ping(9000)", "expected": "2"},
             {"input": "ping(1),ping(3002)", "expected": "1"}],
            "from collections import deque\n\nclass RecentCounter:\n    def __init__(self):\n        # Use a deque to store recent request times\n        pass\n\n    def ping(self, t):\n        # Add t; remove requests older than t-3000\n        # Return deque length\n        pass\n",
            difficulty=0,
        ),
    ],
    "Graph": [
        _q(
            "Number of Islands",
            "Given a 2D grid of '1's (land) and '0's (water), count the number of islands. An island is surrounded by water and formed by connecting adjacent lands horizontally or vertically.",
            [{"input": 'grid=[["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]', "output": "1", "explanation": "All land connects as one island"},
             {"input": 'grid=[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]', "output": "3", "explanation": "Three separate islands"}],
            ["1 ≤ rows, cols ≤ 300", "grid[i][j] is '0' or '1'"],
            "O(m×n)", "O(m×n)",
            [{"input": '[["1","1","0"],["0","1","0"],["0","0","1"]]', "expected": "2"},
             {"input": '[["1","1","1"],["1","1","1"],["1","1","1"]]', "expected": "1"},
             {"input": '[["0","0","0"],["0","0","0"]]', "expected": "0"},
             {"input": '[["1","0","1"],["0","0","0"],["1","0","1"]]', "expected": "4"},
             {"input": '[["1"]]', "expected": "1"}],
            "def num_islands(grid):\n    # DFS/BFS — mark visited cells\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Course Schedule (Cycle Detection)",
            "There are numCourses courses. Given prerequisites pairs [a,b] (must take b before a), return True if you can finish all courses.",
            [{"input": "numCourses=2, prerequisites=[[1,0]]", "output": "True", "explanation": "Take 0 then 1"},
             {"input": "numCourses=2, prerequisites=[[1,0],[0,1]]", "output": "False", "explanation": "Circular dependency"}],
            ["1 ≤ numCourses ≤ 2000", "0 ≤ prerequisites.length ≤ 5000"],
            "O(V+E)", "O(V+E)",
            [{"input": "2, [[1,0]]", "expected": "True"},
             {"input": "2, [[1,0],[0,1]]", "expected": "False"},
             {"input": "1, []", "expected": "True"},
             {"input": "4, [[1,0],[2,0],[3,1],[3,2]]", "expected": "True"},
             {"input": "3, [[0,1],[1,2],[2,0]]", "expected": "False"}],
            "def can_finish(num_courses, prerequisites):\n    # Topological sort / DFS cycle detection\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Find if Path Exists in Graph",
            "Given a bidirectional graph with n nodes and a list of edges, return True if there is a path from source to destination.",
            [{"input": "n=3, edges=[[0,1],[1,2],[2,0]], source=0, destination=2", "output": "True", "explanation": "Path exists: 0->1->2"},
             {"input": "n=6, edges=[[0,1],[0,2],[3,5],[5,4],[4,3]], source=0, destination=5", "output": "False", "explanation": "No path from node 0 to node 5"},
             {"input": "n=1, edges=[], source=0, destination=0", "output": "True", "explanation": "Source equals destination"}],
            ["1 ≤ n ≤ 2×10⁵", "0 ≤ edges.length ≤ 2×10⁵", "0 ≤ source, destination < n"],
            "O(V+E)", "O(V+E)",
            [{"input": "3, [[0,1],[1,2],[2,0]], 0, 2", "expected": "True"},
             {"input": "6, [[0,1],[0,2],[3,5],[5,4],[4,3]], 0, 5", "expected": "False"},
             {"input": "1, [], 0, 0", "expected": "True"},
             {"input": "4, [[0,1],[2,3]], 0, 3", "expected": "False"},
             {"input": "5, [[0,1],[1,2],[2,3],[3,4]], 0, 4", "expected": "True"}],
            "def valid_path(n, edges, source, destination):\n    # BFS/DFS or Union-Find to check connectivity\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Flood Fill",
            "Given an image represented as a 2D grid, a starting pixel (sr, sc), and a new color, perform a flood fill starting from the given pixel. Return the modified image.",
            [{"input": "image=[[1,1,1],[1,1,0],[1,0,1]], sr=1, sc=1, color=2", "output": "[[2,2,2],[2,2,0],[2,0,1]]", "explanation": "All connected 1s from (1,1) are changed to 2"},
             {"input": "image=[[0,0,0],[0,0,0]], sr=0, sc=0, color=0", "output": "[[0,0,0],[0,0,0]]", "explanation": "New color same as old, no change"},
             {"input": "image=[[1]], sr=0, sc=0, color=5", "output": "[[5]]", "explanation": "Single pixel changed"}],
            ["1 ≤ image.length, image[0].length ≤ 50", "0 ≤ image[i][j] ≤ 2¹⁶-1", "0 ≤ color ≤ 2¹⁶-1"],
            "O(m×n)", "O(m×n)",
            [{"input": "[[1,1,1],[1,1,0],[1,0,1]], 1, 1, 2", "expected": "[[2,2,2],[2,2,0],[2,0,1]]"},
             {"input": "[[0,0,0],[0,0,0]], 0, 0, 0", "expected": "[[0,0,0],[0,0,0]]"},
             {"input": "[[1]], 0, 0, 5", "expected": "[[5]]"},
             {"input": "[[1,1,0],[1,0,1]], 0, 0, 3", "expected": "[[3,3,0],[3,0,1]]"},
             {"input": "[[0,1,0],[1,1,1],[0,1,0]], 1, 1, 2", "expected": "[[0,2,0],[2,2,2],[0,2,0]]"}],
            "def flood_fill(image, sr, sc, color):\n    # DFS from starting cell; replace connected same-color cells\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Rotting Oranges",
            "In a grid, 0=empty, 1=fresh orange, 2=rotten orange. Every minute, fresh oranges adjacent to rotten ones become rotten. Return the minimum minutes until no fresh orange remains, or -1 if impossible.",
            [{"input": "grid=[[2,1,1],[1,1,0],[0,1,1]]", "output": "4", "explanation": "Takes 4 minutes for all oranges to rot"},
             {"input": "grid=[[2,1,1],[0,1,1],[1,0,1]]", "output": "-1", "explanation": "Bottom-left orange is isolated"},
             {"input": "grid=[[0,2]]", "output": "0", "explanation": "No fresh oranges, 0 minutes needed"}],
            ["1 ≤ grid.length, grid[0].length ≤ 10", "grid[i][j] is 0, 1, or 2"],
            "O(m×n)", "O(m×n)",
            [{"input": "[[2,1,1],[1,1,0],[0,1,1]]", "expected": "4"},
             {"input": "[[2,1,1],[0,1,1],[1,0,1]]", "expected": "-1"},
             {"input": "[[0,2]]", "expected": "0"},
             {"input": "[[1,2]]", "expected": "1"},
             {"input": "[[2,2],[1,1],[0,0],[2,0]]", "expected": "1"}],
            "from collections import deque\n\ndef oranges_rotting(grid):\n    # Multi-source BFS starting from all rotten oranges\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Pacific Atlantic Water Flow",
            "Given an m×n matrix of heights, water can flow to adjacent cells with equal or lower height. Find all cells from which water can reach both the Pacific (top/left borders) and Atlantic (bottom/right borders) oceans.",
            [{"input": "heights=[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", "output": "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]", "explanation": "7 cells can reach both oceans"},
             {"input": "heights=[[1]]", "output": "[[0,0]]", "explanation": "Single cell borders both oceans"}],
            ["m == heights.length", "n == heights[0].length", "1 ≤ m, n ≤ 200", "0 ≤ heights[i][j] ≤ 10⁵"],
            "O(m×n)", "O(m×n)",
            [{"input": "[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", "expected": "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]"},
             {"input": "[[1]]", "expected": "[[0,0]]"},
             {"input": "[[1,1],[1,1]]", "expected": "[[0,0],[0,1],[1,0],[1,1]]"},
             {"input": "[[3,3,3],[3,1,3],[0,2,4]]", "expected": "[[0,0],[0,1],[0,2],[1,2],[2,2]]"},
             {"input": "[[1,2],[4,3]]", "expected": "[[0,1],[1,0],[1,1]]"}],
            "from collections import deque\n\ndef pacific_atlantic(heights):\n    # BFS/DFS backwards from each ocean border (water flows uphill from ocean perspective)\n    # Find intersection of cells reachable from Pacific and Atlantic\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Shortest Path in Binary Matrix",
            "Given an n×n binary matrix grid, return the length of the shortest clear path from (0,0) to (n-1,n-1). A clear path uses only cells with value 0, moving 8-directionally. Return -1 if no path exists.",
            [{"input": "grid=[[0,1],[1,0]]", "output": "2", "explanation": "Diagonal path of length 2"},
             {"input": "grid=[[0,0,0],[1,1,0],[1,1,0]]", "output": "4", "explanation": "Shortest path has 4 cells"},
             {"input": "grid=[[1,0,0],[1,1,0],[1,1,0]]", "output": "-1", "explanation": "Start cell is blocked"}],
            ["n == grid.length == grid[i].length", "1 ≤ n ≤ 100", "grid[i][j] is 0 or 1"],
            "O(n²)", "O(n²)",
            [{"input": "[[0,1],[1,0]]", "expected": "2"},
             {"input": "[[0,0,0],[1,1,0],[1,1,0]]", "expected": "4"},
             {"input": "[[1,0,0],[1,1,0],[1,1,0]]", "expected": "-1"},
             {"input": "[[0]]", "expected": "1"},
             {"input": "[[0,0],[0,0]]", "expected": "2"}],
            "from collections import deque\n\ndef shortest_path_binary_matrix(grid):\n    # BFS from (0,0); explore 8 directions; track distance\n    pass\n",
            difficulty=1,
        ),
    ],
    "Tree": [
        _q(
            "Maximum Depth of Binary Tree",
            "Given the root of a binary tree, return its maximum depth (number of nodes along the longest path from root to farthest leaf).",
            [{"input": "root=[3,9,20,null,null,15,7]", "output": "3", "explanation": "Longest path: 3→20→15 or 3→20→7"},
             {"input": "root=[1,null,2]", "output": "2", "explanation": "Path: 1→2"}],
            ["0 ≤ Number of nodes ≤ 10⁴", "-100 ≤ Node.val ≤ 100"],
            "O(n)", "O(h) — h=height",
            [{"input": "[3,9,20,null,null,15,7]", "expected": "3"},
             {"input": "[1,null,2]", "expected": "2"},
             {"input": "[]", "expected": "0"},
             {"input": "[1]", "expected": "1"},
             {"input": "[1,2,3,4,5]", "expected": "3"}],
            "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef max_depth(root):\n    # Recursive DFS or iterative BFS\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Validate Binary Search Tree",
            "Given root of a binary tree, determine if it is a valid BST. Left subtree values < node < right subtree values.",
            [{"input": "root=[2,1,3]", "output": "True", "explanation": "1<2<3, valid BST"},
             {"input": "root=[5,1,4,null,null,3,6]", "output": "False", "explanation": "Right child 4 < root 5"}],
            ["1 ≤ Number of nodes ≤ 10⁴", "-2³¹ ≤ Node.val ≤ 2³¹-1"],
            "O(n)", "O(n)",
            [{"input": "[2,1,3]", "expected": "True"},
             {"input": "[5,1,4,null,null,3,6]", "expected": "False"},
             {"input": "[1]", "expected": "True"},
             {"input": "[2,2,2]", "expected": "False"},
             {"input": "[5,3,7,1,4,6,8]", "expected": "True"}],
            "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef is_valid_bst(root):\n    # Track min/max bounds during traversal\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Symmetric Tree",
            "Given the root of a binary tree, check whether it is a mirror of itself (symmetric around its center).",
            [{"input": "root=[1,2,2,3,4,4,3]", "output": "True", "explanation": "Tree is symmetric: left mirrors right"},
             {"input": "root=[1,2,2,null,3,null,3]", "output": "False", "explanation": "Not symmetric: right side differs"},
             {"input": "root=[1]", "output": "True", "explanation": "Single node is symmetric"}],
            ["1 ≤ Number of nodes ≤ 1000", "-100 ≤ Node.val ≤ 100"],
            "O(n)", "O(h)",
            [{"input": "[1,2,2,3,4,4,3]", "expected": "True"},
             {"input": "[1,2,2,null,3,null,3]", "expected": "False"},
             {"input": "[1]", "expected": "True"},
             {"input": "[1,2,3]", "expected": "False"},
             {"input": "[1,2,2,3,4,4,3]", "expected": "True"}],
            "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef is_symmetric(root):\n    # Recursively compare left.left with right.right and left.right with right.left\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Path Sum",
            "Given the root of a binary tree and an integer targetSum, return True if there is a root-to-leaf path such that adding all node values along the path equals targetSum.",
            [{"input": "root=[5,4,8,11,null,13,4,7,2,null,null,null,1], targetSum=22", "output": "True", "explanation": "Path 5->4->11->2 sums to 22"},
             {"input": "root=[1,2,3], targetSum=5", "output": "False", "explanation": "No root-to-leaf path sums to 5"},
             {"input": "root=[], targetSum=0", "output": "False", "explanation": "Empty tree has no paths"}],
            ["0 ≤ Number of nodes ≤ 5000", "-1000 ≤ Node.val ≤ 1000", "-1000 ≤ targetSum ≤ 1000"],
            "O(n)", "O(h)",
            [{"input": "[5,4,8,11,null,13,4,7,2,null,null,null,1], 22", "expected": "True"},
             {"input": "[1,2,3], 5", "expected": "False"},
             {"input": "[], 0", "expected": "False"},
             {"input": "[1,2], 1", "expected": "False"},
             {"input": "[1,2], 3", "expected": "True"}],
            "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef has_path_sum(root, target_sum):\n    # DFS: subtract node value from target as you descend\n    # Return True when leaf reached with remaining sum == 0\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Binary Tree Level Order Traversal",
            "Given the root of a binary tree, return the level order traversal of its nodes' values as a list of lists (left to right, level by level).",
            [{"input": "root=[3,9,20,null,null,15,7]", "output": "[[3],[9,20],[15,7]]", "explanation": "Three levels: root, children, grandchildren"},
             {"input": "root=[1]", "output": "[[1]]", "explanation": "Single node, one level"},
             {"input": "root=[]", "output": "[]", "explanation": "Empty tree has no levels"}],
            ["0 ≤ Number of nodes ≤ 2000", "-1000 ≤ Node.val ≤ 1000"],
            "O(n)", "O(n)",
            [{"input": "[3,9,20,null,null,15,7]", "expected": "[[3],[9,20],[15,7]]"},
             {"input": "[1]", "expected": "[[1]]"},
             {"input": "[]", "expected": "[]"},
             {"input": "[1,2,3,4,5]", "expected": "[[1],[2,3],[4,5]]"},
             {"input": "[1,null,2,null,3]", "expected": "[[1],[2],[3]]"}],
            "from collections import deque\n\nclass TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef level_order(root):\n    # BFS with a queue; collect nodes level by level\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Invert Binary Tree",
            "Given the root of a binary tree, invert the tree (mirror it), and return its root.",
            [{"input": "root=[4,2,7,1,3,6,9]", "output": "[4,7,2,9,6,3,1]", "explanation": "Left and right subtrees swapped at every node"},
             {"input": "root=[2,1,3]", "output": "[2,3,1]", "explanation": "Children swapped"},
             {"input": "root=[]", "output": "[]", "explanation": "Empty tree stays empty"}],
            ["0 ≤ Number of nodes ≤ 100", "-100 ≤ Node.val ≤ 100"],
            "O(n)", "O(h)",
            [{"input": "[4,2,7,1,3,6,9]", "expected": "[4,7,2,9,6,3,1]"},
             {"input": "[2,1,3]", "expected": "[2,3,1]"},
             {"input": "[]", "expected": "[]"},
             {"input": "[1]", "expected": "[1]"},
             {"input": "[1,2,null]", "expected": "[1,null,2]"}],
            "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef invert_tree(root):\n    # Swap left and right children at every node recursively\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Lowest Common Ancestor of BST",
            "Given a BST and two nodes p and q, return their lowest common ancestor (the deepest node that is an ancestor of both p and q).",
            [{"input": "root=[6,2,8,0,4,7,9,null,null,3,5], p=2, q=8", "output": "6", "explanation": "LCA of 2 and 8 is the root 6"},
             {"input": "root=[6,2,8,0,4,7,9,null,null,3,5], p=2, q=4", "output": "2", "explanation": "LCA of 2 and 4 is 2 (ancestor of itself)"},
             {"input": "root=[2,1], p=2, q=1", "output": "2", "explanation": "Root is the LCA"}],
            ["2 ≤ Number of nodes ≤ 10⁵", "-10⁹ ≤ Node.val ≤ 10⁹", "All values are unique", "p and q exist in the BST"],
            "O(h)", "O(1)",
            [{"input": "[6,2,8,0,4,7,9], p=2, q=8", "expected": "6"},
             {"input": "[6,2,8,0,4,7,9], p=2, q=4", "expected": "2"},
             {"input": "[2,1], p=2, q=1", "expected": "2"},
             {"input": "[6,2,8], p=2, q=8", "expected": "6"},
             {"input": "[5,3,7,1,4], p=1, q=4", "expected": "3"}],
            "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef lowest_common_ancestor(root, p, q):\n    # BST property: if both < root go left; if both > root go right; else root is LCA\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Construct Binary Tree from Preorder and Inorder",
            "Given preorder and inorder traversal arrays of a binary tree, construct and return the binary tree.",
            [{"input": "preorder=[3,9,20,15,7], inorder=[9,3,15,20,7]", "output": "[3,9,20,null,null,15,7]", "explanation": "Root=3, left=9, right subtree=[20,15,7]"},
             {"input": "preorder=[-1], inorder=[-1]", "output": "[-1]", "explanation": "Single node"},
             {"input": "preorder=[1,2,3], inorder=[2,1,3]", "output": "[1,2,3]", "explanation": "Root=1, left=2, right=3"}],
            ["1 ≤ preorder.length ≤ 3000", "preorder.length == inorder.length", "All values are unique"],
            "O(n)", "O(n)",
            [{"input": "[3,9,20,15,7], [9,3,15,20,7]", "expected": "[3,9,20,null,null,15,7]"},
             {"input": "[-1], [-1]", "expected": "[-1]"},
             {"input": "[1,2,3], [2,1,3]", "expected": "[1,2,3]"},
             {"input": "[1,2,4,5,3], [4,2,5,1,3]", "expected": "[1,2,3,4,5]"},
             {"input": "[1], [1]", "expected": "[1]"}],
            "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef build_tree(preorder, inorder):\n    # preorder[0] is always root; find its index in inorder to split left/right\n    # Use a hash map for O(1) inorder lookups\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Binary Tree Right Side View",
            "Given the root of a binary tree, return the values of the nodes you can see from the right side, ordered from top to bottom.",
            [{"input": "root=[1,2,3,null,5,null,4]", "output": "[1,3,4]", "explanation": "Right-most node at each level"},
             {"input": "root=[1,null,3]", "output": "[1,3]", "explanation": "Two levels; rightmost at each"},
             {"input": "root=[]", "output": "[]", "explanation": "Empty tree"}],
            ["0 ≤ Number of nodes ≤ 100", "-100 ≤ Node.val ≤ 100"],
            "O(n)", "O(n)",
            [{"input": "[1,2,3,null,5,null,4]", "expected": "[1,3,4]"},
             {"input": "[1,null,3]", "expected": "[1,3]"},
             {"input": "[]", "expected": "[]"},
             {"input": "[1]", "expected": "[1]"},
             {"input": "[1,2,3,4]", "expected": "[1,3,4]"}],
            "from collections import deque\n\nclass TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef right_side_view(root):\n    # BFS level order; collect the last node of each level\n    pass\n",
            difficulty=1,
        ),
    ],
    "DP": [
        _q(
            "Climbing Stairs",
            "You are climbing a staircase with n steps. Each time you can climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
            [{"input": "n=2", "output": "2", "explanation": "1+1 or 2"},
             {"input": "n=3", "output": "3", "explanation": "1+1+1, 1+2, or 2+1"},
             {"input": "n=1", "output": "1", "explanation": "Only one way: 1 step"}],
            ["1 ≤ n ≤ 45"],
            "O(n)", "O(1)",
            [{"input": "1", "expected": "1"}, {"input": "2", "expected": "2"},
             {"input": "3", "expected": "3"}, {"input": "5", "expected": "8"},
             {"input": "10", "expected": "89"}],
            "def climb_stairs(n):\n    # Fibonacci-style DP\n    pass\n",
            difficulty=0,
        ),
        _q(
            "Coin Change",
            "Given coins of different denominations and amount, return the fewest number of coins needed to make up amount. Return -1 if not possible.",
            [{"input": "coins=[1,5,11], amount=15", "output": "3", "explanation": "5+5+5=15 uses 3 coins"},
             {"input": "coins=[2], amount=3", "output": "-1", "explanation": "Cannot make 3 with only 2s"},
             {"input": "coins=[1], amount=0", "output": "0", "explanation": "0 coins needed for amount 0"}],
            ["1 ≤ coins.length ≤ 12", "1 ≤ coins[i] ≤ 2³¹-1", "0 ≤ amount ≤ 10⁴"],
            "O(amount × coins)", "O(amount)",
            [{"input": "[1,5,11], 15", "expected": "3"},
             {"input": "[2], 3", "expected": "-1"},
             {"input": "[1], 0", "expected": "0"},
             {"input": "[1,2,5], 11", "expected": "3"},
             {"input": "[186,419,83,408], 6249", "expected": "20"}],
            "def coin_change(coins, amount):\n    # Bottom-up DP: dp[i] = min coins for amount i\n    pass\n",
            difficulty=1,
        ),
        _q(
            "House Robber",
            "Given an integer array nums representing the amount of money at each house, return the maximum amount you can rob without robbing two adjacent houses.",
            [{"input": "nums=[1,2,3,1]", "output": "4", "explanation": "Rob house 1 (1) and house 3 (3): 1+3=4"},
             {"input": "nums=[2,7,9,3,1]", "output": "12", "explanation": "Rob houses 1, 3, 5: 2+9+1=12"},
             {"input": "nums=[2,1]", "output": "2", "explanation": "Only one house can be robbed; pick the larger"}],
            ["1 ≤ nums.length ≤ 100", "0 ≤ nums[i] ≤ 400"],
            "O(n)", "O(1)",
            [{"input": "[1,2,3,1]", "expected": "4"},
             {"input": "[2,7,9,3,1]", "expected": "12"},
             {"input": "[2,1]", "expected": "2"},
             {"input": "[0]", "expected": "0"},
             {"input": "[5,1,1,5]", "expected": "10"}],
            "def rob(nums):\n    # dp: track max loot with and without current house\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Longest Common Subsequence",
            "Given two strings text1 and text2, return the length of their longest common subsequence. A subsequence is derived by deleting some characters without changing the order.",
            [{"input": 'text1="abcde", text2="ace"', "output": "3", "explanation": '"ace" is a common subsequence of length 3'},
             {"input": 'text1="abc", text2="abc"', "output": "3", "explanation": "Identical strings, LCS = entire string"},
             {"input": 'text1="abc", text2="def"', "output": "0", "explanation": "No common characters"}],
            ["1 ≤ text1.length, text2.length ≤ 1000", "text1 and text2 consist of lowercase letters"],
            "O(m×n)", "O(m×n)",
            [{"input": '"abcde", "ace"', "expected": "3"},
             {"input": '"abc", "abc"', "expected": "3"},
             {"input": '"abc", "def"', "expected": "0"},
             {"input": '"bl", "yby"', "expected": "1"},
             {"input": '"ezupkr", "ubmrapg"', "expected": "2"}],
            "def longest_common_subsequence(text1, text2):\n    # 2D DP table: dp[i][j] = LCS of text1[:i] and text2[:j]\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Word Break",
            "Given a string s and a dictionary of strings wordDict, return True if s can be segmented into a space-separated sequence of one or more dictionary words.",
            [{"input": 's="leetcode", wordDict=["leet","code"]', "output": "True", "explanation": '"leetcode" = "leet" + "code"'},
             {"input": 's="applepenapple", wordDict=["apple","pen"]', "output": "True", "explanation": '"apple" + "pen" + "apple"'},
             {"input": 's="catsandog", wordDict=["cats","dog","sand","and","cat"]', "output": "False", "explanation": "Cannot fully segment the string"}],
            ["1 ≤ s.length ≤ 300", "1 ≤ wordDict.length ≤ 1000", "1 ≤ wordDict[i].length ≤ 20"],
            "O(n²)", "O(n)",
            [{"input": '"leetcode", ["leet","code"]', "expected": "True"},
             {"input": '"applepenapple", ["apple","pen"]', "expected": "True"},
             {"input": '"catsandog", ["cats","dog","sand","and","cat"]', "expected": "False"},
             {"input": '"a", ["a"]', "expected": "True"},
             {"input": '"abcd", ["ab","cd","abc","d"]', "expected": "True"}],
            "def word_break(s, word_dict):\n    # dp[i] = True if s[:i] can be segmented\n    # For each position check all words ending there\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Jump Game",
            "Given an integer array nums where nums[i] is the maximum jump length at position i, return True if you can reach the last index starting from index 0.",
            [{"input": "nums=[2,3,1,1,4]", "output": "True", "explanation": "Jump 1 from index 0 to 1, then 3 to the last index"},
             {"input": "nums=[3,2,1,0,4]", "output": "False", "explanation": "Always stuck at index 3 with value 0"},
             {"input": "nums=[1]", "output": "True", "explanation": "Already at the last index"}],
            ["1 ≤ nums.length ≤ 10⁴", "0 ≤ nums[i] ≤ 10⁵"],
            "O(n)", "O(1)",
            [{"input": "[2,3,1,1,4]", "expected": "True"},
             {"input": "[3,2,1,0,4]", "expected": "False"},
             {"input": "[1]", "expected": "True"},
             {"input": "[0]", "expected": "True"},
             {"input": "[1,0,1,0]", "expected": "False"}],
            "def can_jump(nums):\n    # Greedy: track the farthest reachable index\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Longest Increasing Subsequence",
            "Given an integer array nums, return the length of the longest strictly increasing subsequence.",
            [{"input": "nums=[10,9,2,5,3,7,101,18]", "output": "4", "explanation": "[2,3,7,101] is the longest increasing subsequence"},
             {"input": "nums=[0,1,0,3,2,3]", "output": "4", "explanation": "[0,1,2,3] has length 4"},
             {"input": "nums=[7,7,7,7,7]", "output": "1", "explanation": "No strictly increasing pair exists"}],
            ["1 ≤ nums.length ≤ 2500", "-10⁴ ≤ nums[i] ≤ 10⁴"],
            "O(n log n)", "O(n)",
            [{"input": "[10,9,2,5,3,7,101,18]", "expected": "4"},
             {"input": "[0,1,0,3,2,3]", "expected": "4"},
             {"input": "[7,7,7,7,7]", "expected": "1"},
             {"input": "[1,3,6,7,9,4,10,5,6]", "expected": "6"},
             {"input": "[1]", "expected": "1"}],
            "import bisect\n\ndef length_of_lis(nums):\n    # Patience sorting: maintain a tails array\n    # bisect_left finds where current num fits; replace or extend\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Partition Equal Subset Sum",
            "Given an integer array nums, return True if you can partition it into two subsets with equal sums.",
            [{"input": "nums=[1,5,11,5]", "output": "True", "explanation": "[1,5,5] and [11] both sum to 11"},
             {"input": "nums=[1,2,3,5]", "output": "False", "explanation": "Cannot split into equal sums"},
             {"input": "nums=[1,1]", "output": "True", "explanation": "Each subset contains one element"}],
            ["1 ≤ nums.length ≤ 200", "1 ≤ nums[i] ≤ 100"],
            "O(n × sum)", "O(sum)",
            [{"input": "[1,5,11,5]", "expected": "True"},
             {"input": "[1,2,3,5]", "expected": "False"},
             {"input": "[1,1]", "expected": "True"},
             {"input": "[3,3,3,4,5]", "expected": "True"},
             {"input": "[1,2,5]", "expected": "False"}],
            "def can_partition(nums):\n    # Target = total_sum / 2; 0/1 knapsack DP\n    # dp[s] = True if sum s is reachable\n    pass\n",
            difficulty=1,
        ),
        _q(
            "Edit Distance",
            "Given strings word1 and word2, return the minimum number of operations (insert, delete, replace one character) required to convert word1 to word2.",
            [{"input": 'word1="horse", word2="ros"', "output": "3", "explanation": "horse→rorse(replace h→r)→rose(remove r)→ros(remove e)"},
             {"input": 'word1="intention", word2="execution"', "output": "5", "explanation": "5 operations needed"},
             {"input": 'word1="", word2="abc"', "output": "3", "explanation": "Insert all 3 characters"}],
            ["0 ≤ word1.length, word2.length ≤ 500", "word1 and word2 consist of lowercase letters"],
            "O(m×n)", "O(m×n)",
            [{"input": '"horse", "ros"', "expected": "3"},
             {"input": '"intention", "execution"', "expected": "5"},
             {"input": '"", "abc"', "expected": "3"},
             {"input": '"abc", ""', "expected": "3"},
             {"input": '"abc", "abc"', "expected": "0"}],
            "def min_distance(word1, word2):\n    # 2D DP: dp[i][j] = edit distance of word1[:i] and word2[:j]\n    # dp[i][j] = dp[i-1][j-1] if chars match, else 1 + min(insert, delete, replace)\n    pass\n",
            difficulty=2,
        ),
        _q(
            "Decode Ways",
            "A string of digits maps to letters: '1'→'A', ..., '26'→'Z'. Given a string s of digits, return the number of ways to decode it.",
            [{"input": 's="12"', "output": "2", "explanation": '"AB" (1,2) or "L" (12)'},
             {"input": 's="226"', "output": "3", "explanation": '"BZ" (2,26), "VF" (22,6), "BBF" (2,2,6)'},
             {"input": 's="06"', "output": "0", "explanation": '"06" cannot be decoded (leading zero)'}],
            ["1 ≤ s.length ≤ 100", "s contains only digits", "s may contain leading zeros"],
            "O(n)", "O(n)",
            [{"input": '"12"', "expected": "2"},
             {"input": '"226"', "expected": "3"},
             {"input": '"06"', "expected": "0"},
             {"input": '"1"', "expected": "1"},
             {"input": '"11106"', "expected": "2"}],
            "def num_decodings(s):\n    # dp[i] = ways to decode s[:i]\n    # Single digit valid if != '0'; two digits valid if in [10,26]\n    pass\n",
            difficulty=1,
        ),
    ],
    "OOP": [
        _q(
            "Design LRU Cache",
            "Design a data structure that follows the LRU (Least Recently Used) eviction policy. Implement get(key) and put(key, value) both in O(1).",
            [{"input": "LRUCache(2); put(1,1); put(2,2); get(1); put(3,3); get(2)", "output": "-1", "explanation": "Key 2 was evicted as LRU when 3 was inserted"},
             {"input": "LRUCache(1); put(2,1); get(2); put(3,2); get(2); get(3)", "output": "1,-1,2", "explanation": "Cache size 1 evicts on every put"}],
            ["1 ≤ capacity ≤ 3000", "0 ≤ key ≤ 10⁴", "0 ≤ value ≤ 10⁵", "O(1) per operation"],
            "O(1)", "O(capacity)",
            [{"input": "cap=2,put(1,1),put(2,2),get(1),put(3,3),get(2)", "expected": "-1"},
             {"input": "cap=2,put(1,1),put(2,2),put(1,10),get(1)", "expected": "10"},
             {"input": "cap=1,put(1,1),get(1)", "expected": "1"},
             {"input": "cap=2,get(1)", "expected": "-1"},
             {"input": "cap=3,put(1,1),put(2,2),put(3,3),get(2),put(4,4),get(1)", "expected": "-1"}],
            "from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity):\n        # Use OrderedDict for O(1) LRU tracking\n        pass\n\n    def get(self, key):\n        # Return value or -1 if not found\n        pass\n\n    def put(self, key, value):\n        # Insert/update and evict LRU if over capacity\n        pass\n",
            difficulty=2,
        ),
        _q(
            "Design HashMap",
            "Design a HashMap without using built-in hash table libraries. Implement put(key, val), get(key), and remove(key).",
            [{"input": "put(1,1); put(2,2); get(1); get(3); put(2,1); get(2); remove(2); get(2)", "output": "1,-1,1,-1", "explanation": "Basic map operations"},
             {"input": "put(0,0); get(0); remove(0); get(0)", "output": "0,-1", "explanation": "Remove then get returns -1"}],
            ["0 ≤ key, value ≤ 10⁶", "At most 10⁴ calls", "get returns -1 if key absent"],
            "O(1) average", "O(n)",
            [{"input": "put(1,1),get(1)", "expected": "1"},
             {"input": "put(1,1),get(3)", "expected": "-1"},
             {"input": "put(2,2),put(2,5),get(2)", "expected": "5"},
             {"input": "put(1,1),remove(1),get(1)", "expected": "-1"},
             {"input": "put(0,0),get(0)", "expected": "0"}],
            "class MyHashMap:\n    def __init__(self):\n        # Use chaining or open addressing\n        pass\n\n    def put(self, key, value):\n        pass\n\n    def get(self, key):\n        # Return value or -1\n        pass\n\n    def remove(self, key):\n        pass\n",
            difficulty=1,
        ),
        _q(
            "Implement Stack Using Queues",
            "Implement a LIFO stack using only two queues. Implement push, pop, top, and empty operations.",
            [{"input": "push(1); push(2); top(); pop(); empty()", "output": "2, 2, False", "explanation": "top/pop return the last pushed element"},
             {"input": "push(1); pop(); empty()", "output": "1, True", "explanation": "After popping only element, stack is empty"}],
            ["1 ≤ x ≤ 9", "At most 100 calls total", "pop and top called only on non-empty stacks"],
            "O(n) push, O(1) pop/top", "O(n)",
            [{"input": "push(1),push(2),top()", "expected": "2"},
             {"input": "push(1),push(2),pop()", "expected": "2"},
             {"input": "push(1),pop(),empty()", "expected": "True"},
             {"input": "push(3),push(4),pop(),top()", "expected": "3"},
             {"input": "push(5),empty()", "expected": "False"}],
            "from collections import deque\n\nclass MyStack:\n    def __init__(self):\n        # Use one or two deques to simulate a stack\n        pass\n\n    def push(self, x):\n        # Rotate queue so new element is at front\n        pass\n\n    def pop(self):\n        pass\n\n    def top(self):\n        pass\n\n    def empty(self):\n        pass\n",
            difficulty=0,
        ),
        _q(
            "Design Trie",
            "A trie (prefix tree) is a tree data structure for storing strings. Implement insert, search, and startsWith methods.",
            [{"input": 'insert("apple"); search("apple"); search("app"); startsWith("app"); insert("app"); search("app")', "output": "True,False,True,True", "explanation": '"apple" found, "app" not yet inserted, prefix "app" exists, after inserting "app" it is found'},
             {"input": 'insert("a"); search("a"); startsWith("b")', "output": "True,False", "explanation": '"a" found; no word starts with "b"'}],
            ["1 ≤ word.length ≤ 2000", "word and prefix consist of lowercase English letters", "At most 3×10⁴ calls total"],
            "O(m) per operation — m=word length", "O(m×n) total nodes",
            [{"input": 'insert("apple"),search("apple")', "expected": "True"},
             {"input": 'insert("apple"),search("app")', "expected": "False"},
             {"input": 'insert("apple"),startsWith("app")', "expected": "True"},
             {"input": 'insert("app"),insert("apple"),search("app")', "expected": "True"},
             {"input": 'insert("abc"),startsWith("ab"),startsWith("ac")', "expected": "False"}],
            "class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n\nclass Trie:\n    def __init__(self):\n        self.root = TrieNode()\n\n    def insert(self, word):\n        # Walk/create nodes for each character\n        pass\n\n    def search(self, word):\n        # Return True only if word fully inserted\n        pass\n\n    def startsWith(self, prefix):\n        # Return True if any inserted word starts with prefix\n        pass\n",
            difficulty=1,
        ),
        _q(
            "Design Twitter",
            "Design a simplified Twitter. Users can post tweets, follow/unfollow other users, and see the 10 most recent tweets from users they follow (including themselves).",
            [{"input": "postTweet(1,5); getNewsFeed(1); follow(1,2); postTweet(2,6); getNewsFeed(1); unfollow(1,2); getNewsFeed(1)", "output": "[5], [6,5], [5]", "explanation": "User 1 sees own tweet, then after following user 2 sees both, then after unfollowing sees only own"},
             {"input": "postTweet(1,1); postTweet(2,2); follow(1,2); getNewsFeed(1)", "output": "[2,1]", "explanation": "Most recent first: tweet 2 then tweet 1"}],
            ["1 ≤ userId, followerId, followeeId ≤ 500", "0 ≤ tweetId ≤ 10⁴", "At most 3×10⁴ total calls"],
            "O(n log k) getNewsFeed", "O(n)",
            [{"input": "postTweet(1,5),getNewsFeed(1)", "expected": "[5]"},
             {"input": "postTweet(1,5),follow(1,2),postTweet(2,6),getNewsFeed(1)", "expected": "[6,5]"},
             {"input": "postTweet(1,5),follow(1,2),postTweet(2,6),unfollow(1,2),getNewsFeed(1)", "expected": "[5]"},
             {"input": "postTweet(1,1),postTweet(1,2),getNewsFeed(1)", "expected": "[2,1]"},
             {"input": "follow(1,2),getNewsFeed(1)", "expected": "[]"}],
            "import heapq\nfrom collections import defaultdict\n\nclass Twitter:\n    def __init__(self):\n        self.time = 0\n        self.tweets = defaultdict(list)  # userId -> [(time, tweetId)]\n        self.following = defaultdict(set)\n\n    def postTweet(self, userId, tweetId):\n        # Store tweet with timestamp for ordering\n        pass\n\n    def getNewsFeed(self, userId):\n        # Merge-sort tweets from all followed users + self; return top 10\n        pass\n\n    def follow(self, followerId, followeeId):\n        pass\n\n    def unfollow(self, followerId, followeeId):\n        pass\n",
            difficulty=2,
        ),
        _q(
            "Word Search",
            "Given an m×n grid of characters and a word, return True if the word exists in the grid. The word must be formed from sequentially adjacent cells (horizontally or vertically). Each cell may be used only once.",
            [{"input": 'board=[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word="ABCCED"', "output": "True", "explanation": "Path A→B→C→C→E→D exists"},
             {"input": 'board=[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word="SEE"', "output": "True", "explanation": "S→E→E path at bottom right"},
             {"input": 'board=[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word="ABCB"', "output": "False", "explanation": "Cannot reuse cell B"}],
            ["m == board.length", "n == board[i].length", "1 ≤ m, n ≤ 6", "1 ≤ word.length ≤ 15", "board and word consist of uppercase letters"],
            "O(m×n×4^L) — L=word length", "O(L)",
            [{"input": '[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "ABCCED"', "expected": "True"},
             {"input": '[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "SEE"', "expected": "True"},
             {"input": '[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "ABCB"', "expected": "False"},
             {"input": '[["A"]], "A"', "expected": "True"},
             {"input": '[["A","B"],["C","D"]], "ABDC"', "expected": "True"}],
            "def exist(board, word):\n    # DFS with backtracking; mark cell as visited by modifying in place, restore after\n    pass\n",
            difficulty=1,
        ),
    ],
}


def _topics_for_company(company: str) -> list[str] | None:
    return COMPANY_TOPICS.get(company.strip().lower())


def get_concept_questions_list(concept: str = "", company: str = "") -> list[dict]:
    key = concept.strip() if concept else None
    if key and key in CONCEPT_QUESTIONS:
        pool = CONCEPT_QUESTIONS[key]
        return [{"index": i, "title": q["title"], "difficulty": q["difficulty"], "topic": key}
                for i, q in enumerate(pool)]

    company_topics = _topics_for_company(company) if company else None

    result = []
    for topic in (company_topics or CONCEPTS):
        if topic not in CONCEPT_QUESTIONS:
            continue
        for i, q in enumerate(CONCEPT_QUESTIONS[topic]):
            result.append({"index": i, "title": q["title"], "difficulty": q["difficulty"], "topic": topic})
    # fill in any remaining topics not already listed (when no company filter)
    if not company_topics:
        pass  # CONCEPTS already covers all
    return result


def coding_question(topics: list[str], index: int, language: str, concept: str = "", company: str = "") -> dict:
    pool_key = concept.strip() if concept else None
    if pool_key and pool_key in CONCEPT_QUESTIONS:
        pool = CONCEPT_QUESTIONS[pool_key]
        topic = pool_key
    else:
        company_topics = _topics_for_company(company) if company else None
        preferred = company_topics or topics or list(CONCEPT_QUESTIONS.keys())
        valid_topics = [t for t in preferred if t in CONCEPT_QUESTIONS]
        if not valid_topics:
            valid_topics = list(CONCEPT_QUESTIONS.keys())
        pool = [q for t in valid_topics for q in CONCEPT_QUESTIONS[t]]
        topic = valid_topics[index % len(valid_topics)]

    template = pool[index % len(pool)]
    starter_code = template["starter_code"].get(language, template["starter_code"]["python"])
    return {
        "index": index, "topic": topic, "title": template["title"],
        "description": template["description"], "examples": template["examples"],
        "constraints": template["constraints"], "time_complexity": template["time_complexity"],
        "space_complexity": template["space_complexity"], "test_cases": template["test_cases"],
        "starter_code": starter_code, "difficulty": template["difficulty"],
    }
